#TODO: Add alternate version with YAML anchors in a config_optimized.yml file

# .circleci/config.yml
version: 2.1
jobs:
  build-and-test:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output
      - store_test_results:
          path: output/scan

  adhoc:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  testflight:
    macos:
      xcode: 12.4.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: testflight
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  deploy:
      macos:
        xcode: 12.4.0
      environment:
        FL_OUTPUT_DIR: output
        FASTLANE_LANE: deploy
      steps:
        - checkout
        - run: bundle install
        - run:
            name: Fastlane
            command: bundle exec fastlane $FASTLANE_LANE
        - store_artifacts:
            path: output

workflows:
  build-test-adhoc:
    jobs:
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test
      - deploy:
          requires:
            - build-and-test
      - testflight:
          requires:
            - build-and-test