# The Deliverfile allows you to store various App Store Connect metadata
# For more information, check out the docs
# https://docs.fastlane.tools/actions/deliver/


app_review_information(
  first_name: "Jennings",
  last_name: "Treutel",
  phone_number: "+81 090 1234 5678",
  email_address: "jennings@circleci.com",
  demo_user: "demoUser",
  demo_password: "demoPass",
  notes: "Lorem ipsum dolor sit amet."
)